### ISSUE TITLE
In compatible with other filter modules?

### ISSUE THREAD

**Issue by markvictor** [aurmil/magento-customize-price-filter#13]
Is there any way to get this module working with any other custom filter modules? I'm currently trying to get it working with <a href="http://www.magentocommerce.com/magento-connect/multiple-select-in-layered-navigation-filters.html">this one</a> but having no luck.

I got both displaying but because of the way they apply the filters to the collection they seem incompatible? Any help?

**Comment by aurmil** [comment]
hello

you're right, both modules **don't** work together

the other module defines a class **Mana_Filters_Model_Filter_Price** that extends **Mage_Catalog_Model_Layer_Filter_Price**, as does mine
and it forces the usage of this specific class in the filters
this class overrides method **_getItemsData()**, as does mine

so, sorry but these 2 modules **can't** work together

**Comment by markvictor** [comment]
That's understandable, is there any way to get this working so that you can select more than one filter at once, or work with another module that could allow selected more than one filter at a time?

**Comment by aurmil** [comment]
first option: modify my extension to manage many price ranges at once
technically possible, may be one day I will do this
but right now, unfortunately, I just can tell you that I won't have time to code this until a long time (have a work, extension coding is on free time)
I keep a note about it

second option: work together with another extension
I have to admit that I don't know, it depends on how each extensions is made
I don't know if an extension that just allow to select multi values per filter would have to extend anyway the Price Filter class as my extension
if extending the same class is mandatory, no, it won't work, otherwise, may be it would be possible
but I can't give you an exact answer about this, sorry

**Comment by aurmil** [comment]
PS: if you have knowledge/time/desire, feel free to submit a PR from a fork of this repo for adding first option to the extension, as I won't be able to do it on my own in a decent time frame
